[project]
name = "data-club"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "altair>=6.0.0",
    "arviz>=0.23.4",
    "beautifulsoup4>=4.14.3",
    "cartopy>=0.25.0",
    "contextily>=1.7.0",
    "dask>=2026.1.2",
    "faker>=40.4.0",
    "geopandas>=1.1.2",
    "geoplot>=0.5.1",
    "holoviews>=1.22.1",
    "hvplot>=0.12.2",
    "jupyter>=1.1.1",
    "jupyterlab>=4.5.7",
    "lxml>=6.0.2",
    "marimo>=0.19.9",
    "metpy>=1.7.1",
    "nltk>=3.9.2",
    "polars>=1.38.1",
    "pony>=0.7.19",
    "pymc>=5.27.1",
    "pymongo>=4.16.0",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
    "spacy>=3.8.11",
    "textacy>=0.13.0",
    "tqdm>=4.67.3",
    "vegafusion>=2.0.3",
    "vl-convert-python>=1.9.0.post1",
    "xarray>=2026.1.0",
]
